In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x= np.arange(10).reshape(5,2)
y= range(5)

x_train, x_test ,y_train,y_test = train_test_split(x,y)

model = LinearRegression()
model.fit(x_train,y_train)
model.predict(x_test)

array([2.00000000e+00, 2.02615702e-15])

In [6]:
import pickle
with open('pickle_model','wb') as f:
    pickle.dump(model,f)

In [7]:
with open('pickle_model','rb') as f:
    saved_model = pickle.load(f)

In [8]:
saved_model

LinearRegression()

In [9]:
saved_model.predict([[4,5]])

array([2.])

In [10]:
saved_model.predict(x_test)

array([2.00000000e+00, 2.02615702e-15])

In [11]:
import joblib

file= 'joblib_model.sav'
joblib.dump(model,file)

['joblib_model.sav']

In [12]:
joblib_model= joblib.load(file)
joblib_model.predict([[10,11]])

array([5.])

In [13]:
pip install flask

Note: you may need to restart the kernel to use updated packages.


In [14]:
from flask import Flask, jsonify, request

In [ ]:
app = Flask(__name__)
@app.route('/')
def hello():
    return 'Hello World'



@app.route('/<string:name>')
def helloname(name):
    return 'hello'+ name

@app.route('/<int:x1>/<int:x2>/')
def test(x1,x2):
    f=open('pickle_model','rb')
    saved_model=pickle.load(f)
    prediction=saved_model.predict([[x1,x2]])
    print(prediction)
    return 'Output'+ str(prediction[0])
app.run(host='0.0.0.0', port=106)

 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:106
 * Running on http://192.168.83.154:106
Press CTRL+C to quit
127.0.0.1 - - [02/May/2024 11:20:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2024 11:20:06] "GET /9/10/ HTTP/1.1" 200 -


[4.5]


In [ ]:
def test(x1,x2):
    f=open('pickle_model','rb')
    saved_model=pickle.load(f)
    prediction=saved_model.predict([[x1,x2]])
    print(prediction)
    return 'Output'+ str(prediction[0])
test(5,6)